{
  imports = [
    ./docker.nix
    ./flatpak.nix
    ./fonts.nix
    #./greetd.nix
    ./nh.nix
    ./nvidia-drivers.nix
    ./packages.nix
    ./services.nix
    ./steam.nix
    ./system.nix
    ./stylix.nix
    ./thunar.nix
    ./docker.nix
    ./system.nix
    ./thunar.nix
    ./xserver.nix
  ];
}
