name: Validate Pull Request

on:
  pull_request:
    branches: [main]
  workflow_dispatch: # Allow manual trigger

jobs:
  check-flake:
    name: Check flake structure
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v26
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Check flake
        run: nix flake check --no-build

  check-format:
    name: Check Nix formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v26
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Check formatting
        run: nix fmt -- --check .

  build-desktop:
    name: Build desktop configuration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v26
        with:
          extra_nix_config: |
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
            substituters = https://cache.nixos.org/
      - name: Setup Cachix
        uses: cachix/cachix-action@v14
        with:
          name: nix-configurations
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Build desktop configuration
        run: |
          nix build .#nixosConfigurations.desktop.config.system.build.toplevel

  build-macbook-work:
    name: Build macbook work configuration
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v26
        with:
          extra_nix_config: |
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
            substituters = https://cache.nixos.org/
      - name: Setup Cachix
        uses: cachix/cachix-action@v14
        with:
          name: nix-configurations
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Build macbook work configuration
        run: |
          nix build .#darwinConfigurations.work.system

  build-macbook-private:
    name: Build macbook private configuration
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v26
        with:
          extra_nix_config: |
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
            substituters = https://cache.nixos.org/
      - name: Setup Cachix
        uses: cachix/cachix-action@v14
        with:
          name: nix-configurations
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Build macbook private configuration
        run: |
          nix build .#darwinConfigurations.private.system

  build-all:
    needs: [check-flake, check-format, build-desktop, build-macbook-work, build-macbook-private]
    runs-on: ubuntu-latest
    steps:
      - name: Build successful
        run: echo "All configurations built successfully!"